FROM octoblu/meshblu-connector-builder-base:linux-x86

ENV DEBUG meshblu-connector-*

RUN /bin/bash -c 'env HOME=/tmp/cache yarn global add \
 node-gyp \
 node-pre-gyp \
 meshblu-connector-pkger \
 meshblu-connector-uploader-github \
 meshblu-connector-installer-debian'
